"""Initial schema

Revision ID: 3eba8c541f0c
Revises: 
Create Date: 2026-07-10 18:58:47.731232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eba8c541f0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retry_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('base_delay', sa.Integer(), nullable=False),
    sa.Column('max_delay', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'pid', name='uq_worker_hostname_pid')
    )
    op.create_index('ix_workers_last_heartbeat', 'workers', ['last_heartbeat'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_jobs_count', sa.Integer(), nullable=True),
    sa.Column('current_job_ids', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_heartbeats_worker_id_sent', 'worker_heartbeats', ['worker_id', 'sent_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queues',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('concurrency_limit', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('default_retry_strategy', sa.String(length=50), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('retry_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_queue_project_name')
    )
    op.create_index('ix_queues_project_id', 'queues', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('queue_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('claimed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_strategy', sa.String(length=50), nullable=True),
    sa.Column('retry_config', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('parent_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_claimed_by', 'jobs', ['claimed_by'], unique=False)
    op.create_index('ix_jobs_idempotency_key', 'jobs', ['idempotency_key'], unique=True)
    op.create_index('ix_jobs_queue_id_status', 'jobs', ['queue_id', 'status'], unique=False)
    op.create_index('ix_jobs_status_scheduled_at', 'jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('queue_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('retry_history', sa.JSON(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['original_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_job_id')
    )
    op.create_index('ix_dlq_queue_id_failed_at', 'dead_letter_queue', ['queue_id', 'failed_at'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_executions_job_id', 'job_executions', ['job_id'], unique=False)
    op.create_index('ix_job_executions_worker_id', 'job_executions', ['worker_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_job_id_created', 'job_logs', ['job_id', 'created_at'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_scheduled_jobs_next_run_active', 'scheduled_jobs', ['next_run_at', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_jobs_next_run_active', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index('ix_job_logs_job_id_created', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index('ix_job_executions_worker_id', table_name='job_executions')
    op.drop_index('ix_job_executions_job_id', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('ix_dlq_queue_id_failed_at', table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index('ix_jobs_status_scheduled_at', table_name='jobs')
    op.drop_index('ix_jobs_queue_id_status', table_name='jobs')
    op.drop_index('ix_jobs_idempotency_key', table_name='jobs')
    op.drop_index('ix_jobs_claimed_by', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_queues_project_id', table_name='queues')
    op.drop_table('queues')
    op.drop_table('projects')
    op.drop_index('ix_worker_heartbeats_worker_id_sent', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_table('organizations')
    op.drop_index('ix_workers_last_heartbeat', table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('retry_policies')
    # ### end Alembic commands ###
